BIN = main
OBJECTS = Ingredient.o PizzaIngredientFactory.o PizzaStore.o Pizza.o main.o
CXX = g++
CXXFLAGS = -g

all: $(BIN)

$(BIN): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $@ $^

clean:
	rm -rf $(BIN) $(OBJECTS) core.*
	
